### ISSUE TITLE
AttributeError: 'super' object has no attribute '__torch_dispatch__'

### ISSUE THREAD

**Issue by wang-chen** [albanD/subclass_zoo#27]
Hi, thanks for this great repo to subclass a torch.Tensor.
I have the following error when I try to run many of the scripts in the repo.

* PyTorch version: 1.11.0+cu113
* functorch version: 0.1.0
* On Ubuntu 20.04, with Python 3.8.10

       Traceback (most recent call last):
          File "/home/jeff/workspace/subclass_zoo/python_meta_tensor.py", line 396, in test_embedding_via_mode
            embedding = torch.nn.Embedding(10, 3, device="meta")
          File "/home/jeff/miniconda3/envs/torch-nightly/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 139, in __init__
            self.weight = Parameter(torch.empty((num_embeddings, embedding_dim), **factory_kwargs))
          File "/home/jeff/workspace/subclass_zoo/python_meta_tensor.py", line 91, in __torch_dispatch__
            return super().__torch_dispatch__(func, types, args, kwargs)
        AttributeError: 'super' object has no attribute '__torch_dispatch__'

**Comment by albanD** [comment]
Hi,

I am afraid you will have to use the latest version of pytorch to be able to run this repo as we're constantly building new feature there and incorporating them in the code here.
You can check https://pytorch.org/get-started/locally/ and install the nightly build to get rid of this issue.

On that note, I landed yesterday a major change in core but didn't had time to update the classes here to reflect that. So the nightly from yesterday might have some issues. If that happens, you can always check the download page from the command above directly and select a build from last week end: https://download.pytorch.org/whl/nightly/torch/ look for "20220416" for the builds generated on the 16th of April for example.

**Comment by wang-chen** [comment]
Thank you, installing the latest nightly build for PyTorch (Apr 20, 2022) solves this issue.
