### ISSUE TITLE
`__torch_dispatch__` vs `__torch_function__`

### ISSUE THREAD

**Issue by HanGuo97** [albanD/subclass_zoo#46]
Hi, thanks for this amazing repo!

I have a question regarding the usage of `__torch_dispatch__` and `__torch_function__` in PyTorch. While this repository appears to focus on `__torch_dispatch__`, I haven't been able to find much information on it other than blog posts and discussions on GitHub. On the other hand, PyTorch's documentation only mentions `__torch_function__`.

To my understanding [0][1], `__torch_dispatch__` is used for low-level adjustments, whereas `__torch_function__` serves as syntax sugar. However, the function signatures of both methods are nearly identical, making it unclear which one to use for practitioners who aren't familiar with PyTorch's inner workings.

Could someone please explain the practical differences between these methods? Specifically, when should one use `__torch_dispatch__` versus `__torch_function__`, and what benefits and limitations do each approach offer?

Thanks in advance for your time!

[0] https://dev-discuss.pytorch.org/t/what-and-why-is-torch-dispatch/557
[1] https://github.com/pytorch/pytorch/issues/85826#issuecomment-1267859839

**Comment by albanD** [comment]
Hey!
There is a revamp of the "Extending PyTorch" doc page in progress that covers this topic: https://pytorch.org/docs/main/notes/extending.html#extending-torch-python-api
Happy to get any feedback you might have about this!

**Comment by albanD** [comment]
It is a non-trivial question for sure haha I made this for the PyTorch Conference last year to try to clarify that: https://docs.google.com/presentation/d/1piuv9nBzyoqdH49D1SoE5OZUPSMpOOFqfSKOhr-ab2c/edit#slide=id.p1

The main reasons you should use torch_function I think are either: you need to change the behavior of autograd or you must to override Python API.
If you don't need these, torch_dispatch is usually easier to use indeed as tricky things (like autograd/autocast/etc) already happened and you don't need to worry about them.

I your case, the one question I would ask is: should autograd see your dequant ops or not / should your QuantizedTensor be in the graph itself?
I assume that the answers are no and yes. So you want a torch_dispatch subclass: in spirit, the dequant is an implementation detail of the kernel.

**Comment by HanGuo97** [comment]
The poster and the explanation are very clear! (You should consider putting this on the doc page, btw.) Is there some talk associated with it that I could learn more details about?

I’m closing this issue for now — thanks for all the helps!

**Comment by albanD** [comment]
> You should consider putting this on the doc page, btw.

I waannnttt to do it. But not time yet. This will go at the top of the Extending page!

> Is there some talk associated with it that I could learn more details about?

Not much I'm afraid beyond examples both here, pytorch/pytorch and other repos

**Comment by HanGuo97** [comment]
Looking forward to the new Extending page :)!
