### ISSUE TITLE
`torch.compile`'ed function inside `__torch_dispatch__`

### ISSUE THREAD

**Issue by HanGuo97** [albanD/subclass_zoo#47]
Thanks again for the help last time!

Lately, we've been experimenting with calling some `torch.compile`'ed function side `__torch_dispatch__` for performance reasons. However, I noticed that compiled function does not work well with `__torch_dispatch__`. Here is the code snippet:

```python
import torch
from torch._ops import OpOverload
from torch.utils import _pytree as pytree
from torch.testing._internal import common_subclass
from typing import Tuple, List, Dict, Any, Callable, Type
class ContainerTensor(common_subclass.WrapperTensor):

    @classmethod
    def get_wrapper_properties(
        cls,
        tensor: torch.Tensor,
    ) -> Tuple[torch.Tensor, Dict[str, Any]]:
        return tensor, {}

    def __init__(self, tensor: torch.Tensor) -> None:
        self._tensor = tensor

    # We disable torch function here to avoid any unwanted wrapping of the output
    __torch_function__ = torch._C._disabled_torch_function_impl

    @classmethod
    def __torch_dispatch__(
        cls,
        func: OpOverload,
        types: List[Type],
        args: List[Any],
        kwargs: Dict[str, Any],
    ) -> torch.Tensor:

        @torch.compile
        def f(t):
            return t + 1

        # Unwrap and apply the function
        args_materialized = pytree.tree_map_only(
            ContainerTensor,
            lambda tensor: f(tensor._tensor),
            args)
        return func(*args_materialized, **kwargs)
```

Then the following codes will fail:
```python
A = torch.randn(3, device="cuda")
A_ = ContainerTensor(A)
A_ + 1
```

I'm wondering if there are better ways to call compiled function in such scenario? Thanks in advance for your time again!

**Comment by albanD** [comment]
I'm not so surprised as compile relies on other features that already ran by that point...
The following change makes it work for me (by re-enabling all dispatcher features before calling f), but it might not be what you want.
```python
        def f(t):
            with torch.overrides.enable_reentrant_dispatch():
                @torch.compile
                def f2(t):
                    return t + 1
                return f2(t)
```

cc @bdhirsh will this be magically solve when your PR re-ordering the modes land so that all subclass will now automagically run before FakeMode?

**Comment by HanGuo97** [comment]
Thanks for the pointers -- this works! Is it generally recommended to utilize `enable_reentrant_dispatch` whenever a compiled function is employed (e.g., like the one below)?

I haven't been able to find much documentation or examples of `enable_reentrant_dispatch`, so I am curious if it is safe to use. Are there any unintended consequences that I should be aware of?

```python

class ContainerTensor(common_subclass.WrapperTensor):

    @classmethod
    def __torch_dispatch__(
        cls,
        func: OpOverload,
        types: List[Type],
        args: List[Any],
        kwargs: Dict[str, Any],
    ) -> torch.Tensor:

        with torch.overrides.enable_reentrant_dispatch():
            args_materialized = pytree.tree_map_only(
                ContainerTensor,
                lambda tensor: some_maybe_compiled_function(tensor._tensor),
                args)
        return func(*args_materialized, **kwargs)


@torch.compile
def some_maybe_compiled_function(...):
    ...
```

**Comment by albanD** [comment]
it will re-enable the dispatcher from scratch. So autograd (and any other feature that usually disables itself) will be able to run again.
You can see how this is used for doing two levels of independent autograd in https://github.com/albanD/subclass_zoo/blob/main/nested_forward_ad.py for example.

**Comment by HanGuo97** [comment]
Got it, thanks for the pointers!!

**Comment by HanGuo97** [comment]
Will the PR be merged and released sometime soon?
